<?php

use Illuminate\Database\Seeder;

class MonthTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
          DB::table('months')->insert([
            ['name' => 'Janeiro', 'subpasta_id' => 1],
            ['name' => 'Fevereiro', 'subpasta_id' => 1],
            ['name' => 'Março', 'subpasta_id' => 1],
            ['name' => 'Abril', 'subpasta_id' => 1],
            ['name' => 'Maio', 'subpasta_id' => 1],
            ['name' => 'Junho', 'subpasta_id' => 1],
            ['name' => 'Julho', 'subpasta_id' => 1],
            ['name' => 'Agosto', 'subpasta_id' => 1],
            ['name' => 'Setembro', 'subpasta_id' => 1],
            ['name' => 'Outubro', 'subpasta_id' => 1],
            ['name' => 'Novembro', 'subpasta_id' => 1],
            ['name' => 'Dezembro', 'subpasta_id' => 1],

               ['name' => 'Janeiro', 'subpasta_id' => 2],
            ['name' => 'Fevereiro', 'subpasta_id' => 2],
            ['name' => 'Março', 'subpasta_id' => 2],
            ['name' => 'Abril', 'subpasta_id' => 2],
            ['name' => 'Maio', 'subpasta_id' => 2],
            ['name' => 'Junho', 'subpasta_id' => 2],
            ['name' => 'Julho', 'subpasta_id' => 2],
            ['name' => 'Agosto', 'subpasta_id' => 2],
            ['name' => 'Setembro', 'subpasta_id' => 2],
            ['name' => 'Outubro', 'subpasta_id' => 2],
            ['name' => 'Novembro', 'subpasta_id' => 2],
            ['name' => 'Dezembro', 'subpasta_id' => 2],

               ['name' => 'Janeiro', 'subpasta_id' => 3],
            ['name' => 'Fevereiro', 'subpasta_id' => 3],
            ['name' => 'Março', 'subpasta_id' => 3],
            ['name' => 'Abril', 'subpasta_id' => 3],
            ['name' => 'Maio', 'subpasta_id' => 3],
            ['name' => 'Junho', 'subpasta_id' => 3],
            ['name' => 'Julho', 'subpasta_id' => 3],
            ['name' => 'Agosto', 'subpasta_id' => 3],
            ['name' => 'Setembro', 'subpasta_id' => 3],
            ['name' => 'Outubro', 'subpasta_id' => 3],
            ['name' => 'Novembro', 'subpasta_id' => 3],
            ['name' => 'Dezembro', 'subpasta_id' => 3],

               ['name' => 'Janeiro', 'subpasta_id' => 4],
            ['name' => 'Fevereiro', 'subpasta_id' => 4],
            ['name' => 'Março', 'subpasta_id' => 4],
            ['name' => 'Abril', 'subpasta_id' => 4],
            ['name' => 'Maio', 'subpasta_id' => 4],
            ['name' => 'Junho', 'subpasta_id' => 4],
            ['name' => 'Julho', 'subpasta_id' => 4],
            ['name' => 'Agosto', 'subpasta_id' => 4],
            ['name' => 'Setembro', 'subpasta_id' => 4],
            ['name' => 'Outubro', 'subpasta_id' => 4],
            ['name' => 'Novembro', 'subpasta_id' => 4],
            ['name' => 'Dezembro', 'subpasta_id' => 4],

               ['name' => 'Janeiro', 'subpasta_id' => 2],
            ['name' => 'Fevereiro', 'subpasta_id' => 2],
            ['name' => 'Março', 'subpasta_id' => 2],
            ['name' => 'Abril', 'subpasta_id' => 2],
            ['name' => 'Maio', 'subpasta_id' => 2],
            ['name' => 'Junho', 'subpasta_id' => 2],
            ['name' => 'Julho', 'subpasta_id' => 2],
            ['name' => 'Agosto', 'subpasta_id' => 2],
            ['name' => 'Setembro', 'subpasta_id' => 2],
            ['name' => 'Outubro', 'subpasta_id' => 2],
            ['name' => 'Novembro', 'subpasta_id' => 2],
            ['name' => 'Dezembro', 'subpasta_id' => 2],

               ['name' => 'Janeiro', 'subpasta_id' => 2],
            ['name' => 'Fevereiro', 'subpasta_id' => 2],
            ['name' => 'Março', 'subpasta_id' => 2],
            ['name' => 'Abril', 'subpasta_id' => 2],
            ['name' => 'Maio', 'subpasta_id' => 2],
            ['name' => 'Junho', 'subpasta_id' => 2],
            ['name' => 'Julho', 'subpasta_id' => 2],
            ['name' => 'Agosto', 'subpasta_id' => 2],
            ['name' => 'Setembro', 'subpasta_id' => 2],
            ['name' => 'Outubro', 'subpasta_id' => 2],
            ['name' => 'Novembro', 'subpasta_id' => 2],
            ['name' => 'Dezembro', 'subpasta_id' => 2],

               ['name' => 'Janeiro', 'subpasta_id' => 2],
            ['name' => 'Fevereiro', 'subpasta_id' => 2],
            ['name' => 'Março', 'subpasta_id' => 2],
            ['name' => 'Abril', 'subpasta_id' => 2],
            ['name' => 'Maio', 'subpasta_id' => 2],
            ['name' => 'Junho', 'subpasta_id' => 2],
            ['name' => 'Julho', 'subpasta_id' => 2],
            ['name' => 'Agosto', 'subpasta_id' => 2],
            ['name' => 'Setembro', 'subpasta_id' => 2],
            ['name' => 'Outubro', 'subpasta_id' => 2],
            ['name' => 'Novembro', 'subpasta_id' => 2],
            ['name' => 'Dezembro', 'subpasta_id' => 2],

               ['name' => 'Janeiro', 'subpasta_id' => 2],
            ['name' => 'Fevereiro', 'subpasta_id' => 2],
            ['name' => 'Março', 'subpasta_id' => 2],
            ['name' => 'Abril', 'subpasta_id' => 2],
            ['name' => 'Maio', 'subpasta_id' => 2],
            ['name' => 'Junho', 'subpasta_id' => 2],
            ['name' => 'Julho', 'subpasta_id' => 2],
            ['name' => 'Agosto', 'subpasta_id' => 2],
            ['name' => 'Setembro', 'subpasta_id' => 2],
            ['name' => 'Outubro', 'subpasta_id' => 2],
            ['name' => 'Novembro', 'subpasta_id' => 2],
            ['name' => 'Dezembro', 'subpasta_id' => 2],

               ['name' => 'Janeiro', 'subpasta_id' => 2],
            ['name' => 'Fevereiro', 'subpasta_id' => 2],
            ['name' => 'Março', 'subpasta_id' => 2],
            ['name' => 'Abril', 'subpasta_id' => 2],
            ['name' => 'Maio', 'subpasta_id' => 2],
            ['name' => 'Junho', 'subpasta_id' => 2],
            ['name' => 'Julho', 'subpasta_id' => 2],
            ['name' => 'Agosto', 'subpasta_id' => 2],
            ['name' => 'Setembro', 'subpasta_id' => 2],
            ['name' => 'Outubro', 'subpasta_id' => 2],
            ['name' => 'Novembro', 'subpasta_id' => 2],
            ['name' => 'Dezembro', 'subpasta_id' => 2],

               ['name' => 'Janeiro', 'subpasta_id' => 2],
            ['name' => 'Fevereiro', 'subpasta_id' => 2],
            ['name' => 'Março', 'subpasta_id' => 2],
            ['name' => 'Abril', 'subpasta_id' => 2],
            ['name' => 'Maio', 'subpasta_id' => 2],
            ['name' => 'Junho', 'subpasta_id' => 2],
            ['name' => 'Julho', 'subpasta_id' => 2],
            ['name' => 'Agosto', 'subpasta_id' => 2],
            ['name' => 'Setembro', 'subpasta_id' => 2],
            ['name' => 'Outubro', 'subpasta_id' => 2],
            ['name' => 'Novembro', 'subpasta_id' => 2],
            ['name' => 'Dezembro', 'subpasta_id' => 2],

               ['name' => 'Janeiro', 'subpasta_id' => 2],
            ['name' => 'Fevereiro', 'subpasta_id' => 2],
            ['name' => 'Março', 'subpasta_id' => 2],
            ['name' => 'Abril', 'subpasta_id' => 2],
            ['name' => 'Maio', 'subpasta_id' => 2],
            ['name' => 'Junho', 'subpasta_id' => 2],
            ['name' => 'Julho', 'subpasta_id' => 2],
            ['name' => 'Agosto', 'subpasta_id' => 2],
            ['name' => 'Setembro', 'subpasta_id' => 2],
            ['name' => 'Outubro', 'subpasta_id' => 2],
            ['name' => 'Novembro', 'subpasta_id' => 2],
            ['name' => 'Dezembro', 'subpasta_id' => 2],

               ['name' => 'Janeiro', 'subpasta_id' => 2],
            ['name' => 'Fevereiro', 'subpasta_id' => 2],
            ['name' => 'Março', 'subpasta_id' => 2],
            ['name' => 'Abril', 'subpasta_id' => 2],
            ['name' => 'Maio', 'subpasta_id' => 2],
            ['name' => 'Junho', 'subpasta_id' => 2],
            ['name' => 'Julho', 'subpasta_id' => 2],
            ['name' => 'Agosto', 'subpasta_id' => 2],
            ['name' => 'Setembro', 'subpasta_id' => 2],
            ['name' => 'Outubro', 'subpasta_id' => 2],
            ['name' => 'Novembro', 'subpasta_id' => 2],
            ['name' => 'Dezembro', 'subpasta_id' => 2],
            
           
        ]);
    }
}
